name: Upload Process to Devops-Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Copy Artifacts Directory
      run: |
        cp -r ./Amiya-873/ucd-paac-action/artifactory ./artifactory

    - name: Upload a Process to Devops-Deploy
      uses: Amiya-873/ucd-paac-action@v1.23
      with:
        deployURL: https://192.168.1.6:8443
        username: ${{ secrets.MY_USER }}
        password: ${{ secrets.MY_PASSWORD }}
        inputFileDirectory: ${{ github.workspace }}

    - name: Clean Up
      run: |
        rm -rf artifactory
