name: Upload Process to Devops-Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Checkout Artifacts Directory
      run: |
        git clone --depth=1 --filter=blob:none --sparse https://github.com/Amiya-873/ucd-paac-action.git
        cd ucd-paac-action
        git sparse-checkout set artifacts
        cd ..

    - name: Upload a Process to Devops-Deploy
      uses: Amiya-873/ucd-paac-action@1.34
      with:
        deployURL: https://192.168.1.6:8443
        username: ${{ secrets.MY_USER }}
        password: ${{ secrets.MY_PASSWORD }}
        inputFileDirectory: ${{ github.workspace }}

    - name: Clean Up
      run: |
        rm -rf ucd-paac-action
