name: Upload Process to Devops-Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set file permissions
      run: chmod +x ./artifacts/pacc-0.1.0.9999999-SNAPSHOT/upload-generic-process

    - name: Upload Process to Devops-Deploy
      uses: Amiya-873/ucd-paac-action@v1.17
      with:
        deployURL: https://192.168.1.6:8443
        username: ${{ secrets.MY_USER }}
        password: ${{ secrets.MY_PASSWORD }}
        inputFileDirectory: ${{ github.workspace }}
